[package]
name = "img_ascii"
version = "0.1.0"
authors = ["Luke Thompson <luke@yorkbay.net.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.13"
